# Generated by Django 4.0.6 on 2022-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes')], max_length=10)),
                ('photo', models.FileField(upload_to='uploaded_photo')),
            ],
        ),
    ]
