version: '3.8'

services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_TOKEN=${DJANGO_TOKEN}
    command: python manage.py runserver 0.0.0.0:8000
